name: graphql-api
version: 0.3.0
synopsis: GraphQL API
description: |
  Implement [GraphQL](http://graphql.org/) servers in Haskell.

  Provides a Servant-like type-based API for defining GraphQL schemas and
  implementing handlers for those schemas.

  See [README.md](https://github.com/haskell-graphql/graphql-api#graphql-api) for more details.
author: Jonathan M. Lange, Tom Hunger
maintainer: Jonathan M. Lange <jml@mumak.net>, Tom Hunger <tehunger@gmail.com>
license: Apache
license-file: LICENSE.Apache-2.0
github: haskell-graphql/graphql-api
category: Web
stability: unstable
extra-source-files:
  - CHANGELOG.rst

# NB the "redundant constraints" warning is a GHC bug: https://ghc.haskell.org/trac/ghc/ticket/11099
ghc-options: -Wall -fno-warn-redundant-constraints
default-extensions:
  - DerivingStrategies
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - StandaloneDeriving
  - TypeApplications

dependencies:
  - base >= 4.9 && < 5
  - protolude >= 0.2.1
  - exceptions
  - transformers
  - attoparsec

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - ghc-prim
    - scientific
    - QuickCheck
    - text

executables:
  input-object-example:
    main: InputObject.hs
    source-dirs: examples
    other-modules: []
    dependencies:
      - aeson
      - graphql-api

  union-example:
    main: UnionExample.hs
    source-dirs: examples
    other-modules: []
    dependencies:
      - aeson
      - graphql-api

tests:
  graphql-api-tests:
    main: Main.hs
    source-dirs: tests
    dependencies:
      - aeson
      - containers
      - graphql-api
      - hspec
      - QuickCheck
      - raw-strings-qq
      - directory

  graphql-api-doctests:
    main: Main.hs
    ghc-options: -threaded
    source-dirs: tests/doctests
    dependencies:
      - doctest

benchmarks:
  criterion:
    main: Main.hs
    source-dirs: benchmarks
    dependencies:
      - criterion
      - graphql-api
