name: graphql-api
version: 0.1.0
synopsis: Sketch of GraphQL stuff
description: Please see README.md
maintainer: Jonathan M. Lange <jml@mumak.net>
license: Apache
github: jml/graphql-api
category: Web

# NB the "redundant constraints" warning is a GHC bug: https://ghc.haskell.org/trac/ghc/ticket/11099
ghc-options: -Wall -fno-warn-redundant-constraints
default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards

dependencies:
  - base >= 4.9 && < 5
  - protolude

executables:
  graphql-api-example:
    main: Main.hs
    source-dirs: cmd
    dependencies:
      - graphql-api

library:
  source-dirs: src
  dependencies:
    - aeson
    - containers
    - graphql
    - text
    - attoparsec
    - transformers
    - exceptions

tests:
  graphql-api-tests:
    main: Spec.hs
    source-dirs: tests
    dependencies:
      - aeson
      - containers
      - graphql
      - graphql-api
      - tasty
      - tasty-hspec
